osx_image: beta-xcode6.3
language: objective-c
script:
  - export GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
  - export GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - xctool -project DoTests.xcodeproj -scheme DoTestsTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project DoTests.xcodeproj -scheme DoTestsTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success: slather
